### ISSUE TITLE
Problems with test report output

### ISSUE THREAD

**Issue by martinqvistgard** [quangson91/intellij_rest_cli#18]
Hi! 

Thank you for all your hard work!
I just tested version 1.4, having the ability to supply a list of .http files is awesome and what really makes this a killer app for ci workflows :+1: 

I did find some a couple of issues during testing, though.

When running more than one .http file, there are no results at all in the file specified by -r argument. Instead the results are output in the test-reports folder in files with the same name as the .http file. This makes it hard to integrate with gitlab ci, which as far as I know does not support wildcards for finding report files. The results should, as I see it, all be collected in the file specified by -f.

In case this is the planned behavior, there is a problem with files overwriting each other. In our case, we have several modules in our application and they each have a folder test/HTTP that usually contains a file named ApiTests.http. In this scenario, the report file from the last ApiTests.http file to run will overwrite earlier reports.

**Comment by martinqvistgard** [comment]
Just wanted to let you know that we now have a fully functioning test running in gitlab ci.
With this (partial) config
```
script:
    # Build containers
    - docker-compose -f docker-compose-api-test.yml build
    # Start containers and run  tests
    - docker-compose -f docker-compose-api-test.yml up -d
    - java -jar /restcli.jar -s `pwd`/module/xx/test/HTTP/WorkflowTest.http -r api-report
  artifacts:
    paths:
      - test-reports/api-report.xml
    reports:
      junit: test-reports/api-report.xml
```

We get a fully functioning test run with reports and all :)
![image](https://user-images.githubusercontent.com/703595/90247925-e3860480-de37-11ea-98fc-ba0a98e6811a.png)
