### ISSUE TITLE
--report adds datestamp which causes problems with gitlab ci

### ISSUE THREAD

**Issue by martinqvistgard** [quangson91/intellij_rest_cli#9]
Adding --report="api-report" results in a file named someting like 202008050909_api-report.xml

At least in gitlab ci this causes a problem. report files has to be specified like this:

```yaml
script:
    - java -jar /restcli.jar -s `pwd`/v2/module/PartnerOrder/test/HTTP/WorkflowTest.http -l=NONE -r=api-report.xml
artifacts:
  paths:
    - api-report.xml
  reports:
    junit: api-report.xml
```

Since a timestamp is added to the specified filename gitlab can not find the report file

```
Uploading artifacts for successful job
Uploading artifacts...
WARNING: api-report.xml: no matching files         
ERROR: No files to upload 
```
